---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tinc
  namespace: tinc-system
spec:
  selector:
    matchLabels:
      name: tinc
  template:
    metadata:
      labels:
        name: tinc
    spec:
      serviceAccountName: tinc-node
      hostNetwork: true
      strategy: Recreate
      securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
      containers:
      - name: tinc
        image: stv0g/tinc
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /dev/net/tun
          name: dev-tun
      volumes:
      - hostPath:
          path: /dev/net/tun
          type: CharDevice
        name: dev-tun
