---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tinc-node
  namespace: tinc-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-editor
  namespace: tinc-system
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-secrets
  namespace: tinc-system
subjects:
- kind: ServiceAccount
  name: tinc-node
  namespace: tinc-system
roleRef:
  kind: Role
  name: secret-editor
  apiGroup: rbac.authorization.k8s.io
