---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.riasc.eu
  labels:
    {{- include "riasc.labels" . | nindent 4 }}
spec:
  scope: Cluster
  group: riasc.eu
  names:
    kind: Project
    plural: projects
    singular: project
    shortNames:
    - pro
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              users:
                type: array
                items:
                  type: string

              nodes:
                type: array
                items:
                  type: string

              nodeSelector:
                type: object
                x-kubernetes-preserve-unknown-fields: true

