---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "riasc.fullname" }}-operator
  labels:
    {{- include "riasc.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "riasc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "riasc.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "riasc.fullname" }}-operator
      containers:
      - name: operator
        image: erigrid/riasc-operator
        resources:
          limits:
            cpu: 250m
            memory: 250M
        env:
        - name: ENV
          value: production
        - name: ADMISSION_ADDR
          value: https://{{ include "riasc.fullname" . }}-webhook.{{  .Release.Namespace }}.svc
        - name: ADMISSION_CERTFILE
          value: /cert/tls.crt
        - name: ADMISSION_PKEYFILE
          value: /cetc/tls.key
        ports:
        - containerPort: 443
        volumeMounts:
        - readOnly: true
          mountPath: /cert/
          name: webhook-cert
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
      volumes:
      - name: webhook-cert
        secret:
          secretName: {{ include "riasc.fullname" . }}-webhook-cert
