---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "riasc.fullname" . }}-operator
  labels:
    {{- include "riasc.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "riasc.fullname" . }}-operator
  labels:
    {{- include "riasc.labels" . | nindent 4 }}
rules:
- apiGroups:
  - project.riasc.eu
  resources:
  - projects
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "riasc.fullname" . }}-operator
  labels:
    {{- include "riasc.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "riasc.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "netem.fullname" . }}-operator
  apiGroup: rbac.authorization.k8s.io
