---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "riasc.fullname" . }}-time-sync
  namespace: riasc-system
  labels:
    {{- include "riasc.labels" . | nindent 4 }}
data:

  chrony.conf: |
    user root
    pidfile /run/chronyd.pid

    # Stored on hostpath volume
    driftfile /var/lib/chrony/drift

{{- if .Values.ntp.server.local }}
    local stratum {{ .Values.ntp.server.stratum }}{{ ternary " orphan" "" .Values.ntp.server.orphan }}
{{- end }}

    rtcsync
    makestep 1.0 3
    hwtimestamp *

{{- if .Values.ntp.server.enabled }}
{{- range .Values.ntp.server.allow }}
    allow {{ . }}
{{- end }}
{{- range .Values.ntp.server.deny }}
    deny {{ . }}
{{- end }}
{{- endif }}
    
{{- if .Values.gps.enabled -}}
    # https://chrony.tuxfamily.org/documentation.html
    # https://gpsd.gitlab.io/gpsd/gpsd-time-service-howto.html#_feeding_chrony_from_gpsd
    # gspd is looking for
    # /var/run/chrony.pps0.sock
    refclock SOCK /run/chrony.{{ .Values.gps.device }}.sock refid GPS   precision 1e-1 offset 0.9999
    refclock SOCK /run/chrony.pps0.sock refid PPS0 precision 1e-7 lock GPS
{{- endif }}
{{- if .Values.pps.enabled }}
    refclock PPS  /dev/{{ .Values.pps.device }} refid PPS1 precision 1e-7 lock GPS
{{- endif }}
{{- if .Values.ptp.enabled }}
    refclock PHC  /dev/{{ .Values.ptp.device }} refid PTP1
{{- endif }}
  
    ## NTP servers/peers/pools
{{- range (concat .Values.ntp.servers .Values.defaultServers) }}
    {{ include "riasc.ntp.server" . }}
{{- end }}

    # Logging
    log rawmeasurements measurements statistics tracking refclocks tempcomp
    logdir /var/log/chrony
    logbanner 0
    logchange 0.1

    {{- .Values.chrony.extraConfig | default "" }}

{{- if .Values.ptp.enabled }}
  ptp4l.conf: |
    [global]
    slaveOnly {{ ternary 1 0 .Values.ptp.slaveOnly }}

    network_transport {{ .Values.ptp.transport }}

    verbose {{ ternary 1 0 .Valus.ptp.verbose }}
    logging_level {{ .Values.ptp.loggingLevel }}

    time_stamping {{ .Values.ptp.time_stamping }}

    [{{ .Values.ptp.interface}}]
    # empty

    {{- .Values.ptp.extraConfig | default "" }}
    
{{- end }}
