{{- if .Values.time_sync.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "riasc.fullname" . }}-time-sync
  namespace: riasc-system
  labels:
    {{- include "riasc.labels" . | nindent 4 }}
data:

  chrony.conf: |
    user root
    allow
    pidfile /run/chronyd.pid
    driftfile /var/lib/chrony/drift
    local stratum 1 orphan
    rtcsync
    makestep 1.0 3
    hwtimestamp *
    
    # https://chrony.tuxfamily.org/documentation.html
    # https://gpsd.gitlab.io/gpsd/gpsd-time-service-howto.html#_feeding_chrony_from_gpsd
    # gspd is looking for
    # /var/run/chrony.pps0.sock
    
    refclock SOCK /run/chrony.ttyAMA0.sock  refid GPS   precision 1e-1 offset 0.9999
    refclock SOCK /run/chrony.pps0.sock     refid PPS0  precision 1e-7 lock GPS
    refclock PPS  /dev/pps0                 refid PPS1  precision 1e-7 lock GPS
    # refclock PHC  /dev/ptp0                 refid PTP
    # NTP Servers
    pool   europe.pool.ntp.org    iburst  minpoll 4  maxpoll 4

{{- range .Values.time_sync.ntp.servers }}
    server  {{ . }}  iburst  minpoll 4  maxpoll 4
{{- end }}

    # Some Stratum1 Servers
    # https://www.meinbergglobal.com/english/glossary/public-time-server.htm
    # http://support.ntp.org/bin/view/Servers/StratumOneTimeServers
    
    ## Physikalisch-Technische Bundesanstalt (PTB), Braunschweig, Germany
    server  ptbtime1.ptb.de  iburst  minpoll 4  maxpoll 4
    server  ptbtime2.ptb.de  iburst  minpoll 4  maxpoll 4
    server  ptbtime3.ptb.de  iburst  minpoll 4  maxpoll 4
    
    ## Royal Observatory of Belgium
    server  ntp1.oma.be  iburst  minpoll 4  maxpoll 4
    server  ntp2.oma.be  iburst  minpoll 4  maxpoll 4

    # Logging
    log rawmeasurements measurements statistics tracking refclocks tempcomp
    logdir /var/log/chrony
    logbanner 0
    logchange 0.1
{{- end }}
