---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: riasc-system
  name: {{ include "time-sync.fullname" $ }}-{{ .name }}
  labels:
    {{- include "time-sync.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: ntp
  template:
    metadata:
      labels:
        name: ntp
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .name }}
      serviceAccount: time-sync
      hostNetwork: true # for IEEE1588/PTP
      containers:
      - name: chrony
        image: erigrid/time-sync
        command:
        - /bin/sh
        args:
        - -c
        - rm -f /run/chronyd.pid; chronyd -dd -f /etc/chrony.conf
        securityContext:
          privileged: true
          # capabilities:
          #   add:
          #   - SYS_TIME
        volumeMounts:
        - mountPath: /dev
          name: dev
        - mountPath: /etc/chrony.conf
          name: config
          subPath: chrony.conf
          readOnly: true
        - mountPath: /run/
          name: run
        - mountPath: /var/lib/chrony
          name: var

      - name: status
        image: erigrid/time-sync
        volumeMounts:
        - mountPath: /run/
          name: run
        - mountPath: /var/lib/chrony
          name: var-chrony

{{- if .Values.gps.enabled -}}
      - name: gpsd
        image: erigrid/time-sync
        command:
        - /bin/sh
        args:
        - -c
        - while [ ! -S /run/chrony.$(GPS_DEVICE).sock ]; do \
            sleep 1;
          done;
          sleep 1;
          gpsd -n -N -D4 /dev/$(GPS_DEVICE)
        env:
        - name: GPS_DEVICE
          value: {{ .Values.gps.device | quote }}
        securityContext:
          privileged: true
          # capabilities:
          #   add:
          #   - SYS_NICE
        volumeMounts:
        - mountPath: /dev
          name: dev
        - mountPath: /run/
          name: run
{{- end }}
{{- if .Values.ptp.enabled }}
      - name: ptp4l
        image: erigrid/time-sync
        command:
        - ptp4l
        args: [
          '-f', '/etc/ptp4l.conf'
        ]
        env:
        - name: PTP_INTERFACE
          value: {{ .Values.ptp.interface | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev
          name: dev
        - mountPath: /run/
          name: run
        - mountPath: /etc/ptp4l.conf
          name: config
          subPath: ptp4l.conf
          readOnly: true
{{- end }}
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: config
        configMap:
          name: {{ include "time-sync.fullname" $ }}
      - name: run
        emptyDir:
      - name: var-chrony
        hostPath:
          path: /var/lib/chrony
          type: DirectoryOrCreate
