---
openapi: 3.1.0
info:
  title: RIasC Time-sync API
  description: An API for querying the status of the Chrony time synchronization and GPSd daemons on a RIasC node.
  version: 0.1.0
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server

paths:
  /config:
    get:
      summary: Get current configuration
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              example: {}
              schemas:
                $ref: '#/components/schemas/Config'

  /status:
    get:
      summary: Get status of time synchronization and GPSd daemons
      responses:
        '200':
          description: The current status of the ttime synchronization daemons
          content:
            application/json:
              example: {}
              schemas:
                $ref: '#/components/schemas/Status'

  /status/synced:
    get:
      summary: Check if the node is synchronized

      responses:
        '200':
          description: The node is synchronized

        '500':
          description: The node is not synchronized

components:
  schemas:
    Status:
      type: object
      properties:
        gpsd:
          type: object
          properties: {}

        chrony:
          type: object
          properties:
