{{- range .Values.projects }}
{{- $fullname := printf "%s-%s" (include "riasc.fullname" $) .name }}
---
apiVersion: riasc.eu/v1
kind: Project
metadata:
  name: {{ .name }}
spec:
  users: {{ .users | default list | toYaml }}
  nodes: {{ .nodes | default list | toYaml }}
  nodeSelector: {{ .nodeSelector | default dict | toYaml }}
{{- end }}
