{{- range $name, $secret := .Values.secrets }}
{{- if $secret.external | default false | not }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "riasc.labels" $ | nindent 4 }}
data:
  {{- if .yaml }}
  file: {{ .yaml | toYaml | b64enc }}
  {{- else if .json }}
  file: {{ .json | toJson | b64enc }}
  {{- else if .content }}
  file: {{ .content | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
