# Default values for time-sync.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

configurations:
- selector:
    matchLabels:
      kubernetes.io/hostname: infis-pi

  chrony:
    # Extra content for Chrony configuration file
    #  See: https://manpages.debian.org/bullseye/chrony/chrony.conf.5.en.html
    extraConfig: null

  pps:
    enabled: true

    # Kernel PPS device (e.g. /dev/pps0)
    device: pps0

    # GPIO pin which is providing PPS input
    pin: 18

  ptp:
    enabled: true

    # The local clock is a slave-only clock if enabled.
    slaveOnly: true

    # The maximum logging level of messages which should be printed.
    loggingLevel: 6 # LOG_INFO

    # Print messages to the standard output if enabled.
    verbose: false

    # Network interface which is used for PTP sync.
    interface: eth0

    # Select the network transport.
    # Possible values are UDPv4, UDPv6 and L2.
    transport: UDPv4

    # The time stamping method.
    # The allowed values are hardware, software and legacy.
    timestamping: hardware

    # The PTP Hardware clock device (PHC)
    device: ptp0

    # Extra content for PTP4L configuration file
    #  See: https://manpages.debian.org/bullseye/linuxptp/ptp4l.8.en.html
    extraConfig: null

  gps:
    enabled: true

    # The serial device of the GPS receiver (e.g. /dev/ttyAMA0)
    device: ttyAMA0

    # Additional commandline options passed to GPSd
    #  See: https://manpages.debian.org/bullseye/gpsd/gpsd.8.en.html
    extraArgs: []
    
  ntp:
    client:
      enabled: true

    server:
      enabled: true

      local: true
      stratum: 1
      orphan: true

      # Access control list
      allow:
      - 0.0.0.0/0
      - ::/0

      deny: []

    servers:
    - type: server
      address: ntp1.rwth-aachen.de
      minPoll: 3
      maxPoll: 3
    - type: server
      address: ntp2.rwth-aachen.de

    defaultServers:
    # ntp.org pool
    - type: pool
      address: europe.pool.ntp.org

    # Some Stratum1 Servers
    # https://www.meinbergglobal.com/english/glossary/public-time-server.htm
    # http://support.ntp.org/bin/view/Servers/StratumOneTimeServers
    
    ## Physikalisch-Technische Bundesanstalt (PTB), Braunschweig, Germany
    - type: server
      address: ptbtime1.ptb.de
    - type: server
      address: ptbtime2.ptb.de
    - type: server
      address: ptbtime3.ptb.de
    
    ## Royal Observatory of Belgium
    - type: server
      address: ntp1.oma.be
    - type: server
      address: ntp2.oma.be
