---

traffic-profiles:
- name: example-profile

  # Supported types: "Builtin", "Script" & "Flexe" (VTT) 
  type: Script

  # Type-dependent profile parameters
  parameters:
    netem:
      delay: 200000

  # A selector which matches the pods which should be subject to this profile
  podSelector:
    matchLabels:
      traffic-profile: delay-jitter-to-quad-one

  # Ingress and Egress filters are inspired by Kubernetes' NetworkPolicy Resource
  #  See: https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource
  egress:
  - to:
    - ipBlock:
        cidr: 1.1.1.1/32
    - podSelector:
        matchLabels:
          component: example
    ports:
    - port: 443
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 0
      protocol: ICMP

  - ports:
    - port: 80
      protocol: tcp

  ingress:
  - ports:
    - port: 1234
  - from:
    - podSelector:
        matchLabels:
          traffic-profile: delay-jitter-to-quad-one

# Cluster-external devices
# devices:
# - name: rwth-abb-pmu-1
#   external_ip: 134.130.169.123

services: {}
configs: {}
secrets: {}
volumes: {}
