---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netem.fullname" . }}-webhook
  labels:
    {{- include "netem.labels" . | nindent 4 }}
  namespace: riasc-system
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "netem.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "netem.selectorLabels" . | nindent 8 }}
      name: webhook
    spec:
      serviceAccountName: {{ include "netem.fullname" . }}
      automountServiceAccountToken: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
      - name: webhook
        command: ['k8s-netem-webhook']
        image: erigrid/netem:latest
        imagePullPolicy: Always
        env:
        - name: DEBUG
          value: '1'
        ports:
        - containerPort: 443
        volumeMounts:
        - readOnly: true
          mountPath: /certs
          name: webhook-cert
        readinessProbe:
          httpGet:
            path: /health
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
      volumes:
      - name: webhook-cert
        secret:
          secretName: {{ include "netem.fullname" . }}-webhook-cert
