---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-netem
  labels:
    {{- include "netem.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-netem
  labels:
    {{- include "netem.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8s-netem.riasc.eu
  resources:
  - trafficprofiles
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - watch
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-netem
  labels:
    {{- include "netem.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: k8s-netem
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: default
  namespace: my-app
roleRef:
  kind: ClusterRole
  name: k8s-netem
  apiGroup: rbac.authorization.k8s.io
