---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netem.fullname" . }}
  labels:
    {{- include "netem.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "netem.fullname" . }}
  labels:
    {{- include "netem.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8s-netem.riasc.eu
  resources:
  - trafficprofiles
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "netem.fullname" . }}
  labels:
    {{- include "netem.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "netem.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "netem.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
