---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trafficprofile-reader
  labels:
    {{- include "netem.labels" . | nindent 4 }}

rules:
- apiGroups: ["k8s-netem.riasc.eu"]
  resources: ["trafficprofiles"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trafficprofile-reader
  labels:
    {{- include "netem.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: k8s-netem
  namespace: riasc-system
roleRef:
  kind: ClusterRole
  name: trafficprofile-reader
  apiGroup: rbac.authorization.k8s.io
