---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "netem.fullname" . }}-webhook
  labels:
    {{- include "netem.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "netem.selectorLabels" . | nindent 4 }}
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
