---
kind: Service
apiVersion: v1
metadata:
  name: k8s-netem-webhook
  labels:
    {{- include "netem.labels" . | nindent 4 }}
spec:
  selector:
    app: k8s-netem-webhook
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
