{{- $cn := "k8s-netem-webhook.riasc-system.svc" -}}
{{- $ca := genCA "netem-admission-ca" 3650 -}}
{{- $cert := genSignedCert $cn nil (list $cn) 3650 $ca -}}
---
kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: k8s-netem-webhook
  labels:
    {{- include "netem.labels" . | nindent 4 }}
webhooks:
- name: k8s-netem-webhook.riasc-system.svc
  sideEffects: None
  admissionReviewVersions:
  - "v1"
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Ignore
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      namespace: riasc-system
      name: k8s-netem-webhook
      path: /mutate
      port: 443

---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-netem-webhook-cert
  labels:
    {{- include "netem.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
