---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: local-bridge
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "eth0",
            "ipam": {
              "type": "dhcp"
            }
        }'

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-case-01
  annotations:
    k8s.v1.cni.cncf.io/networks: local-bridge
spec:
  nodeSelector:
    kubernetes.io/hostname: rpi-aurelius-1
  containers:
  - name: pod-case-01
    image: nginx
